package za.ac.tendertrack.data.repo

import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Columns
import io.github.jan.supabase.postgrest.query.Order
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import za.ac.tendertrack.core.Format
import za.ac.tendertrack.data.SupabaseModule
import za.ac.tendertrack.data.model.*
import za.ac.tendertrack.data.sample.SampleData

/**
 * The shape written when adding a note. Separate from [FlagNote] because the id
 * and timestamp are generated by the database, not sent by the client.
 */
@kotlinx.serialization.Serializable
private data class FlagNoteInsert(
    @kotlinx.serialization.SerialName("flag_id") val flagId: String,
    val author: String,
    val text: String
)

/** Compliance flags and their investigation trail — FR6 to FR8. */
interface FlagRepository {
    suspend fun list(): List<ComplianceFlag>
    suspend fun byId(id: String): ComplianceFlag?
    suspend fun addNote(flagId: String, text: String, author: String): ComplianceFlag
    suspend fun resolve(flagId: String, outcome: FlagOutcome, note: String, author: String): ComplianceFlag
    suspend fun assignToMe(flagId: String, author: String): ComplianceFlag
}

class SupabaseFlagRepository(private val client: SupabaseClient) : FlagRepository {

    override suspend fun list(): List<ComplianceFlag> = withContext(Dispatchers.IO) {
        client.from(SupabaseModule.Table.FLAGS)
            .select(Columns.raw("*, notes:flag_notes(*)")) {
                order("raised_at", Order.DESCENDING)
            }
            .decodeList()
    }

    override suspend fun byId(id: String): ComplianceFlag? = withContext(Dispatchers.IO) {
        client.from(SupabaseModule.Table.FLAGS)
            .select(Columns.raw("*, notes:flag_notes(*)")) {
                filter { eq("id", id) }
                limit(1)
            }
            .decodeSingleOrNull()
    }

    override suspend fun addNote(flagId: String, text: String, author: String): ComplianceFlag =
        withContext(Dispatchers.IO) {
            client.from(SupabaseModule.Table.FLAG_NOTES)
                .insert(FlagNoteInsert(flagId = flagId, author = author, text = text))
            byId(flagId) ?: error("Flag not found.")
        }

    override suspend fun resolve(
        flagId: String,
        outcome: FlagOutcome,
        note: String,
        author: String
    ): ComplianceFlag = withContext(Dispatchers.IO) {
        client.from(SupabaseModule.Table.FLAGS)
            .update({
                set("status", "resolved")
                set("outcome", outcome.name.lowercase())
            }) { filter { eq("id", flagId) } }
        addNote(flagId, "Resolved — ${outcome.displayName}. $note", author)
    }

    override suspend fun assignToMe(flagId: String, author: String): ComplianceFlag =
        withContext(Dispatchers.IO) {
            client.from(SupabaseModule.Table.FLAGS)
                .update({
                    set("assigned_to", author)
                    set("status", "under_investigation")
                }) { filter { eq("id", flagId) } }
            byId(flagId) ?: error("Flag not found.")
        }
}

class SampleFlagRepository : FlagRepository {

    override suspend fun list(): List<ComplianceFlag> =
        SampleData.flags.sortedByDescending { it.raisedAt }

    override suspend fun byId(id: String): ComplianceFlag? = SampleData.flags.firstOrNull { it.id == id }

    override suspend fun addNote(flagId: String, text: String, author: String): ComplianceFlag =
        replace(flagId) { flag ->
            flag.copy(
                notes = flag.notes + FlagNote(
                    id = "n-${System.currentTimeMillis()}",
                    author = author,
                    text = text,
                    createdAt = Format.nowIso()
                )
            )
        }

    override suspend fun resolve(
        flagId: String,
        outcome: FlagOutcome,
        note: String,
        author: String
    ): ComplianceFlag = replace(flagId) { flag ->
        flag.copy(
            status = FlagStatus.RESOLVED,
            notes = flag.notes + FlagNote(
                id = "n-${System.currentTimeMillis()}",
                author = author,
                text = "Resolved — ${outcome.displayName}. $note",
                createdAt = Format.nowIso()
            )
        )
    }

    override suspend fun assignToMe(flagId: String, author: String): ComplianceFlag =
        replace(flagId) { flag ->
            flag.copy(status = FlagStatus.UNDER_INVESTIGATION, assignedTo = author)
        }

    private fun replace(id: String, transform: (ComplianceFlag) -> ComplianceFlag): ComplianceFlag {
        val index = SampleData.flags.indexOfFirst { it.id == id }
        require(index >= 0) { "Flag not found." }
        val updated = transform(SampleData.flags[index])
        SampleData.flags[index] = updated
        return updated
    }
}
